name: Certora

on:
  push:
    branches:
      - main
      - certora/workflow
  pull_request:
    branches:
      - main

jobs:
  verify_launch_high_level:
    uses: ./.github/workflows/certora_setup.yml
    with:
      verify_name:   Verify LaunchEvent High Level
      verify_script: certora/scripts/verifyLEHighLevel.sh
      verify_rules:
        - hl_EqualityOfToken
        - hl_depositAdditivity
        - hl_withdrawAdditivity
        - hl_twoSideInverse
        - hl_noDepositFrontRun
        - hl_noWithdrawLiquidityFrontRun
        - hl_stoppedOnlySwitch
        - hl_onlyOwnerSwitch
        - hl_whatShouldRevert
        - hl_noWithdrawFrontRun
    secrets:
      CERTORAKEY: ${{ secrets.CERTORAKEY }}


#   verify_launch_valid_states:
#     runs-on: ubuntu-latest
#     needs: install
#     strategy:
#       matrix:
#         rule:
#           - factoryGetPairCorrelationCurrentVals
#           - cl_pairAndGetPairCorrelation
#           - al_issuerAllocationZero
#           - al_balanceLessThanAllocation
#           - al_userAllocationLessThanMaxAllocation
#           - al_issuerTimelockNonZero
#           - al_userTimelockSeven
#           - al_timelocksCorrelation
#           - op_incentivesCorrelation
#           - op_userNotWithdrawnPair
#           - op_userNotWithdrawnIncentives
#           - op_wavaxBalanceAndSumBalances
#           - op_avaxAllocZero
#           - op_lpSupplyZero
#           - op_PairBalanceIsZero
#           - op_PairAndTotalSupplyCorrelation
#           - op_AvaxCorrelation
#           - op_tokenCorrelation
#           - op_tokenResFixed
#           - cl_avaxAllocSumUserBalances
#           - cl_avaxReservCheck
#           - cl_incentivesCorrelation
#           - cl_userAllocUnchanging
#           - cl_avaxAllocUnchanging
#           - cl_userBalanceFixed 
#           - cl_lpSupplyFixed
#           - cl_AvaxCorrelation
#           - os_tokenCorrelation
#           - os_avaxAllocSumUserBalances
#           - os_avaxReserveDecrease
#           - os_userBalanceNonIncreasing
#           - cs_lpSupplyFixed
#           - cs_userBalanceFixed
#           - cs_avaxAllocatedFixed
# 
#     steps:
#       - name: Download artifacts
#         uses: actions/download-artifact@v3
# 
#       - name: Verify valid-state rule ${{ matrix.rule }}
#         run:  sh certora/scripts/verifyLEValidStates.sh ${{ matrix.rule }}
# 
#   verify_staking:
#     runs-on: ubuntu-latest
#     needs: install
#     steps:
#       - name: Download artifacts
#         uses: actions/download-artifact@v3
# 
#       - name: Verify staking rules
#         run:  sh certora/scripts/verifyStaking.sh
# 
