name: Certora

on:
  push:
    branches:
      - main
      - certora/workflow
  pull_request:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up node.js
        uses: actions/setup-node@v2
        with: { node-version: "16.x", check-latest: true }

      - name: Install node dependencies
        run:  yarn

      - name: Install python
        uses: actions/setup-python@v2
        with: { python-version: 3.6 }

      - name: Install java
        uses: actions/setup-java@v1
        with: { java-version: "11", java-package: jre }

      - name: Install solc
        run: |
          wget https://github.com/ethereum/solidity/releases/download/v0.8.6/solc-static-linux
          chmod +x solc-static-linux
          sudo mv solc-static-linux /usr/local/bin/solc8.6

      - name: Install certora
        run: pip install certora-cli

      - name: Create munged files
        run: make -C certora/ munged

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: certora
          path: certora/

  verify_launch_high_level:
    runs-on: ubuntu-latest
    needs: install
    strategy:
      matrix:
        rule:
          - hl_EqualityOfToken
          - hl_depositAdditivity
          - hl_withdrawAdditivity
          - hl_twoSideInverse
          - hl_noDepositFrontRun
          - hl_noWithdrawLiquidityFrontRun
          - hl_stoppedOnlySwitch
          - hl_onlyOwnerSwitch
          - hl_whatShouldRevert
          - hl_noWithdrawFrontRun
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Verify high-level rule ${{ matrix.rule }}
        run: sh certora/scripts/verifyLEHighLevel.sh ${{ matrix.rule }}
        env:
          CERTORAKEY: ${{ secrets.CERTORAKEY }}


  verify_launch_valid_states:
    runs-on: ubuntu-latest
    needs: install
    strategy:
      matrix:
        rule:
          - factoryGetPairCorrelationCurrentVals
          - cl_pairAndGetPairCorrelation
          - al_issuerAllocationZero
          - al_balanceLessThanAllocation
          - al_userAllocationLessThanMaxAllocation
          - al_issuerTimelockNonZero
          - al_userTimelockSeven
          - al_timelocksCorrelation
          - op_incentivesCorrelation
          - op_userNotWithdrawnPair
          - op_userNotWithdrawnIncentives
          - op_wavaxBalanceAndSumBalances
          - op_avaxAllocZero
          - op_lpSupplyZero
          - op_PairBalanceIsZero
          - op_PairAndTotalSupplyCorrelation
          - op_AvaxCorrelation
          - op_tokenCorrelation
          - op_tokenResFixed
          - cl_avaxAllocSumUserBalances
          - cl_avaxReservCheck
          - cl_incentivesCorrelation
          - cl_userAllocUnchanging
          - cl_avaxAllocUnchanging
          - cl_userBalanceFixed 
          - cl_lpSupplyFixed
          - cl_AvaxCorrelation
          - os_tokenCorrelation
          - os_avaxAllocSumUserBalances
          - os_avaxReserveDecrease
          - os_userBalanceNonIncreasing
          - cs_lpSupplyFixed
          - cs_userBalanceFixed
          - cs_avaxAllocatedFixed

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Verify valid-state rule ${{ matrix.rule }}
        run:  sh certora/scripts/verifyLEValidStates.sh ${{ matrix.rule }}

  verify_staking:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Verify staking rules
        run:  sh certora/scripts/verifyStaking.sh

